const btnwrapper = document.querySelector('btnwrapper')
const right = document.querySelector('right')
const left = document.querySelector('left')
const rub1 = document.querySelector("rub1")
const rub2 = document.querySelector("rub2")
const usd1 = document.querySelector("usd1")
const usd2 = document.querySelector("usd2")
const eur1 = document.querySelector("eur1")
const eur2 = document.querySelector("eur2")
const gbp1 = document.querySelector("gbp1")
const gbp2 = document.querySelector("gbp2")
let input1=document.querySelector("#input1")
let input2=document.querySelector("#input2")
let show1=document.querySelector("#show1")
let show2=document.querySelector("#show2")

rub1.addEventListener('click', changeActive)
usd1.addEventListener('click',changeActive)
eur1.addEventListener('click',changeActive)
gbp1.addEventListener('click',changeActive)

rub2.addEventListener('click', changeActive)
usd2.addEventListener('click', changeActive)
eur2.addEventListener('click', changeActive)
gbp2.addEventListener('click', changeActive)
